'use client';
import {useState} from 'react';
import {api} from '../mirror-client.mjs';
export default function Manage(){
 const [key,setKey]=useState(''),[ready,setReady]=useState(false),[codes,setCodes]=useState([]),[issued,setIssued]=useState([]),[batch,setBatch]=useState('闲鱼首发'),[count,setCount]=useState(10),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState(null);
 const act=async fn=>{setBusy(true);setNotice('');try{await fn();}catch(e){setNotice(e.message);}finally{setBusy(false);}};
 const refresh=async()=>{const data=await api('admin/codes',undefined,key);setCodes(data.codes);setReady(true);};
 const issue=()=>act(async()=>{const data=await api('admin/issue',{count:Number(count),batch},key);setIssued(data.codes);setNotice('已生成。完整兑换码仅在本次显示，请立即下载保存；列表只保留尾号。');await refresh();});
 const mutate=()=>act(async()=>{await api('admin/'+pending.action,{id:pending.id},key);setPending(null);await refresh();setNotice('已更新。');});
 const download=()=>{const contents='兑换码,编号\n'+issued.map(c=>c.code+','+c.id).join('\n');const url=URL.createObjectURL(new Blob(['\ufeff'+contents],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='股市照妖镜兑换码.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <main className="shell manage"><header><a className="brand" href="/">◉ 股市照妖镜</a><span>兑换码管理</span></header><h1>把故事，交到买家手里。</h1><p>一码首次绑定一个浏览器，解锁本季十五关及身份卡，可重复体验。</p>{!ready?<form onSubmit={e=>{e.preventDefault();act(refresh);}}><label htmlFor="admin-key">管理密钥</label><input id="admin-key" type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} className="code-input"/><button className="primary" disabled={busy||!key}>{busy?'正在验证…':'进入管理'}</button><p className="fine">密钥仅用于管理，请勿发给买家。</p></form>:<><div className="admin-actions"><button className="secondary" onClick={()=>act(refresh)} disabled={busy}>刷新状态</button><button className="text-button" onClick={()=>{setKey('');setReady(false);setCodes([]);setIssued([]);}}>退出管理</button></div><section className="admin-box"><h2>生成一批兑换码</h2><form onSubmit={e=>{e.preventDefault();issue();}}><label htmlFor="batch-name">批次名称</label><input id="batch-name" className="code-input" value={batch} maxLength={60} onChange={e=>setBatch(e.target.value)}/><label htmlFor="count">数量（1—100）</label><input id="count" className="code-input" type="number" min="1" max="100" value={count} onChange={e=>setCount(e.target.value)}/><button className="primary" disabled={busy||issued.length>0}>生成兑换码</button></form>{issued.length>0&&<div><p>完整码只显示这一次。先下载，再关闭这批结果。</p><button className="secondary" onClick={download}>下载这批 CSV</button><pre className="issued-codes">{issued.map(c=>c.code).join('\n')}</pre><button className="text-button" onClick={()=>setIssued([])}>已保存，关闭本批结果</button></div>}</section><section className="admin-box"><h2>最近 500 个兑换码</h2><p className="fine">停用会立即撤销访问；重置会解除旧浏览器绑定，买家可以用原码重新兑换。</p><div className="table-scroll"><table><thead><tr><th>尾号</th><th>批次</th><th>状态</th><th>兑换时间</th><th>操作</th></tr></thead><tbody>{codes.map(c=><tr key={c.id}><td>…{c.suffix}</td><td>{c.batch}</td><td>{c.status==='revoked'?'已停用':c.claimed_at?'已兑换':'未使用'}</td><td>{c.claimed_at?new Date(c.claimed_at).toLocaleString('zh-CN'):'—'}</td><td><button disabled={busy||c.status==='revoked'} onClick={()=>setPending({id:c.id,action:'revoke',suffix:c.suffix})}>停用</button> <button disabled={busy} onClick={()=>setPending({id:c.id,action:'reset',suffix:c.suffix})}>重置</button></td></tr>)}</tbody></table></div></section>{pending&&<div className="admin-confirm" role="alertdialog" aria-label="确认兑换码操作"><p>确认{pending.action==='revoke'?'停用':'重置'}尾号 {pending.suffix}？原浏览器将失去解锁权限。</p><button className="primary" disabled={busy} onClick={mutate}>确认操作</button><button className="secondary" onClick={()=>setPending(null)}>取消</button></div>}</>}<p className="notice" role="status">{notice}</p></main>;
}
